---
kind: pipeline
type: kubernetes
name: ci

clone:
  depth: 1

steps:
  - name: install
    image: node:16-alpine
    commands:
      - npm ci --legacy-peer-deps --no-audit --no-fund

  - name: build
    image: node:16-alpine
    commands:
      - npm run build
    depends_on:
      - install

  - name: lint
    image: node:16-alpine
    commands:
      - npm run lint
    depends_on:
      - install

  - name: code-style
    image: node:16-alpine
    commands:
      - npm run code-style
    depends_on:
      - install

  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: SLACK_WEBHOOK
      channel:
        from_secret: SLACK_CHANNEL
      link_names: true
      icon_emoji: nani
      username: Drone
      template: >
        {{#success build.status}}
        ✅ SUIT UI DOCS
        {{else}}
        ❌ SUIT UI DOCS
        {{/success}}

        *Type*: {{ build.event }}

        *Branch*: {{ build.branch }}

        *Author*: {{ build.author }}     

        *Message*: ${DRONE_COMMIT_MESSAGE}

        *Commit*: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}>

        *Branch*: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}|{{ build.branch }}>

        *Time*: {{since build.started}}

        *Status*: {{ build.status }}

        *Link*: {{ build.link }}

    when:
      status:
        - success
        - failure
      event:
        - push
        - pull_request
    depends_on:
      - build
      - lint
      - code-style

trigger:
  branch:
    - master
  event:
    - pull_request
    - push
